name: Release
on:
  workflow_dispatch:
  push:
    tags:
      - v*

env:
  MIHON_GITHUB_RELEASE: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get_tag:
    if: github.repository == 'sj0404-collab/yomihon-custom' || github.repository == 'yomihon/yomihon'
    name: Extract tag name
    runs-on: 'ubuntu-24.04'
    outputs:
      tag: ${{ steps.extract.outputs.tag }}

    steps:
      - name: Get tag name
        id: extract
        run: echo "tag=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

  build:
    if: github.repository == 'sj0404-collab/yomihon-custom' || github.repository == 'yomihon/yomihon'
    name: Build
    runs-on: 'ubuntu-24.04'
    timeout-minutes: 20
    needs: [get_tag]

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up JDK
        uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # v5.5.0
        with:
          java-version-file: .github/.java-version
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0

      - name: Build
        run: ./gradlew assembleRelease -Pinclude-telemetry -Penable-updater --stacktrace
        env:
          RELEASE_TAG: ${{ needs.get_tag.outputs.tag }}
          storeFileBase64: ${{ secrets.SIGNING_KEY }}
          storePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyAlias: ${{ secrets.ALIAS }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Rename APK
        run: |
          set -e

          mv app/build/outputs/apk/release/app-armeabi-v7a-release.apk yomihon-armeabi-v7a-${{ needs.get_tag.outputs.tag }}.apk
          mv app/build/outputs/apk/release/app-arm64-v8a-release.apk yomihon-arm64-v8a-${{ needs.get_tag.outputs.tag }}.apk
          mv app/build/outputs/apk/release/app-x86-release.apk yomihon-x86-${{ needs.get_tag.outputs.tag }}.apk
          mv app/build/outputs/apk/release/app-x86_64-release.apk yomihon-x86_64-${{ needs.get_tag.outputs.tag }}.apk
          mv app/build/outputs/apk/release/app-universal-release.apk yomihon-universal-${{ needs.get_tag.outputs.tag }}.apk

      - name: Upload APK
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: yomihon
          path: |
            yomihon-armeabi-v7a-${{ needs.get_tag.outputs.tag }}.apk
            yomihon-arm64-v8a-${{ needs.get_tag.outputs.tag }}.apk
            yomihon-x86-${{ needs.get_tag.outputs.tag }}.apk
            yomihon-x86_64-${{ needs.get_tag.outputs.tag }}.apk
            yomihon-universal-${{ needs.get_tag.outputs.tag }}.apk

  build_foss:
    if: github.repository == 'sj0404-collab/yomihon-custom' || github.repository == 'yomihon/yomihon'
    name: Build (FOSS)
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    needs: [get_tag]

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up JDK
        uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # v5.5.0
        with:
          java-version-file: .github/.java-version
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
        with:
          cache-disabled: true

      - name: Build
        run: ./gradlew assembleFoss -Penable-updater
        env:
          RELEASE_TAG: ${{ needs.get_tag.outputs.tag }}
          storeFileBase64: ${{ secrets.SIGNING_KEY }}
          storePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyAlias: ${{ secrets.ALIAS }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Rename APK
        run: |
          set -e

          mv app/build/outputs/apk/foss/app-universal-foss.apk yomihon-${{ needs.get_tag.outputs.tag }}-foss.apk

      - name: Upload APK
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: yomihon-foss
          path: yomihon-${{ needs.get_tag.outputs.tag }}-foss.apk

  release:
    if: github.repository == 'sj0404-collab/yomihon-custom' || github.repository == 'yomihon/yomihon'
    name: Create GitHub Release
    runs-on: ubuntu-24.04
    needs: [get_tag, build, build_foss]
    permissions:
      contents: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          merge-multiple: true

      - name: Delete all artifacts
        uses: geekyeggo/delete-artifact@176a747ab7e287e3ff4787bf8a148716375ca118 # v6.0.0
        with:
          failOnError: false
          name: |
            yomihon
            yomihon-foss

      - name: Create GitHub Release
        uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b # v3.0.1
        with:
          tag_name: ${{ needs.get_tag.outputs.tag }}
          name: Yomihon ${{ needs.get_tag.outputs.tag }}
          body: |
            Check out the [past release notes](https://github.com/yomihon/yomihon/releases) if you’re upgrading from an earlier version.

            <!-->



            <!-->

            > [!TIP]
            >
            > ### If you are unsure which version to download then go with `yomihon-universal-${{ needs.get_tag.outputs.tag }}.apk`
          files: |
            yomihon-armeabi-v7a-${{ needs.get_tag.outputs.tag }}.apk
            yomihon-arm64-v8a-${{ needs.get_tag.outputs.tag }}.apk
            yomihon-x86-${{ needs.get_tag.outputs.tag }}.apk
            yomihon-x86_64-${{ needs.get_tag.outputs.tag }}.apk
            yomihon-universal-${{ needs.get_tag.outputs.tag }}.apk
            yomihon-${{ needs.get_tag.outputs.tag }}-foss.apk
          draft: true
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
